spring:
  config:
    import: optional:dotenv
  datasource:
    # point at TimescaleDB
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: ${API_USER:admin}
      password: ${API_PASSWORD:admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  ping:
    cron: "*/10 * * * * *"
    host: "8.8.8.8"
